DevCard_Mvc/Models/Article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevCard_Mvc.Models
{
    public class Article
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string  Description { get; set; }
        public string Image { get; set; }
        public Article(long id,string title,string description,string image)
        {
            Id = id;
            Title = title;
            Description = description;
            Image = image;
        }
    }
    
}

DevCard_Mvc/Models/Contact.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DevCard_Mvc.Models
{
    public class Contact
    {
        [Required(ErrorMessage ="این فیلد اجباری است.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "این فیلد اجباری است.")]
        [EmailAddress(ErrorMessage="ایمیل معتبر نیست.")]
        public string  Email { get; set; }
        public string Message { get; set; }
        public int Service { get; set; }
        public SelectList Services { get; set; }
        
    }
}

DevCard_Mvc/Models/ErrorViewModel.cs
using System;

namespace DevCard_Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DevCard_Mvc/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevCard_Mvc.Models
{
    public class Project
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Client { get; set; }

        public Project(long id, string name, string description, string image, string client)
        {
            Id = id;
            Name = name;
            Description = description;
            Image = image;
            Client = client;
        }
    }
}

DevCard_Mvc/Models/Services.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevCard_Mvc.Models
{
    public class Services
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Services(int id,string name)
        {
            Id = id;
            Name = name;
        }
    }
}

DevCard_Mvc/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DevCard_Mvc.Models;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using DevCard_Mvc.Data;

namespace DevCard_Mvc.Controllers
{
    public class HomeController : Controller
    {

        private readonly List<Services> _services = new List<Services>{
         
            new Services( 1,"طلایی"),
            new Services( 2,"نقره ای"),
            new Services( 3,"الماس"),
            new Services( 4,"برنز"),
        };

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult contact()
        {
            var contact = new Contact
            {
                Services = new SelectList(_services, "Id", "Name")
            };
            return View(contact);
        }
        [HttpPost]
        public IActionResult contact(Contact contact)
        {


            contact = new Contact
            {
                Services = new SelectList(_services, "Id", "Name")
            };

            if (!ModelState.IsValid)
            {
                ViewBag.Error = "اطلاعات وارد شده صحیح نیست.";
                return View(contact);
            }
            ModelState.Clear();

            ViewBag.Success = "عملیات با موفقیت انجام شد.";
            return View(contact);

        }
        
        public IActionResult Details(long id)
        {
            var projects = ProjectStore.GetProjectById(id);
            return View(projects);
        }
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DevCard_Mvc/ViewComponents/ArticlesViewComponent.cs
using DevCard_Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevCard_Mvc.ViewComponents
{
    public class ArticlesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var articles = new List<Article>
            {
                new Article(1,"آموزش جاوا","یکی از بهترین زبان ها برای برنامه نویسی اندروید به حساب می آید.","blog-post-thumb-1.jpg"),
                new Article(2,"آموزش طاحی سایت با bootstrap","فریمورک بوت استرپ واکنش گرایی سایت ما رو به سادگی تامین می کنه","blog-post-thumb-2.jpg"),
                new Article(3,"آموزش  طراحی رزومه حرفه ای","فریمورک بوت استرپ واکنش گرایی سایت ما رو به سادگی تامین می کنه","blog-post-thumb-3.jpg")

            };
            return View("_Articles",articles);
        }
    }
}

DevCard_Mvc/ViewComponents/ProjectsViewComponent.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using DevCard_Mvc.Data;

namespace DevCard_MVC.ViewComponents
{
    public class ProjectsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var projects = ProjectStore.Projects();
            return View("_Projects", projects);
        }
    }
}

DevCard_Mvc/Views/Home/Components/Articles/_Articles.cshtml
@model IEnumerable<DevCard_Mvc.Models.Article>

    <section class="latest-blog-section p-3 p-lg-5">
        <div class="container">
            <h2 class="section-title font-weight-bold mb-5">آخرین مقالات</h2>
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-md-4 mb-5">
                        <div class="card blog-post-card">
                            <img class="card-img-top" src="assets/images/blog/@item.Image" alt="image">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a class="theme-link" href="blog-post.html">
                                       @item.Title
                                    </a>
                                </h5>
                                <p class="card-text">
                                    @item.Description
                                </p>
                                <p class="mb-0"><a class="more-link" href="blog-post.html">ادامه مطلب</a></p>

                            </div>
                        </div>
                    </div>

                }

            </div>
        </div>
    </section>

DevCard_Mvc/Views/Home/Components/Projects/View.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

DevCard_Mvc/Views/Home/Components/Projects/_Projects.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<DevCard_MVC.Models.Project>
<section class="featured-section p-3 p-lg-5">
    <div class="container">
        <h2 class="section-title font-weight-bold mb-5">خاص ترین پروژه ها</h2>
        <div class="row">
            @foreach (var item in Model)
            {
            <div class="col-md-6 mb-5">
                <div class="card project-card">
                    <div class="row no-gutters">
                        <div class="col-lg-4 card-img-holder">
                            <img src="~/assets/images/project/@item.Image" class="card-img" alt="image">
                        </div>
                        <div class="col-lg-8">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href="/home/Details/@item.Id" class="theme-link">
                                       @item.Name
                                    </a>
                                </h5>
                                <p class="card-text">
                                   @item.Description
                                </p>
                                <p class="card-text"><small class="text-muted">سفارش دهنده: @item.Client</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</section>

DevCard_Mvc/Views/Home/Contact.cshtml
@model Contact
@{
    ViewData["Title"] = "Contact";
}

<section class="cta-section theme-bg-light py-5">    
    <div class="container text-center single-col-max-width">
        <h2 class="heading">ارتباط با ما</h2>
        <div class="intro">
            <p>
                شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
                نوشته و ارسال کنید.
            </p>
           
            <p>از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
            <ul class="list-inline mb-0">
                <li class="list-inline-item mb-3">
                    <a class="twitter" href="#">
                        <i class="fab fa-twitter fa-fw fa-lg"></i>
                    </a>
                </li>

                <li class="list-inline-item mb-3">
                    <a class="linkedin" href="#">
                        <i class="fab fa-linkedin-in fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="github" href="#">
                        <i class="fab fa-github-alt fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="instagram" href="#">
                        <i class="fab fa-instagram fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="stack-overflow" href="#">
                        <i class="fab fa-stack-overflow fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="medium" href="#">
                        <i class="fab fa-medium-m fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="codepen" href="#">
                        <i class="fab fa-codepen fa-fw fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div>
        </div>
        </section>

<section class="contact-section px-3 py-5 p-md-5">
    <div class="container">
        @if (!string.IsNullOrWhiteSpace(ViewBag.Success))
        {
            <div class="alert-success p-2">
                <p>@ViewBag.Success</p>
            </div>
        }
        @if (!string.IsNullOrWhiteSpace(ViewBag.Error))
        {
            <div class="alert-danger p-2">
                <p>@ViewBag.Error</p>
            </div>
        }

        <form asp-action="Contact" id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post">
            <h3 class="text-center mb-3">در دسترس باشید!</h3>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Name">نام</label>
                    <input type="text" class="form-control" asp-for="Name" placeholder="نام">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Email">ایمیل</label>
                    <input type="email" class="form-control" asp-for="Email" placeholder="ایمیل">
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group col-12">
                    <select id="services" class="custom-select" asp-items="Model.Services" name="services">
                        <option selected>سرویس مورد نظر خود را انتخاب کنید...</option>
                       
                    </select>
                </div>
                <div class="form-group col-12">
                    <label class="sr-only" asp-for="Message">پیغام شما</label>
                    <textarea class="form-control" id="cmessage" asp-for="Message"
                              placeholder="پیغام خود را وارد نمایید ..." rows="10"></textarea>
                </div>
                <div class="form-group col-12">
                    <button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
                </div>
            </div>
        </form>
    </div>
</section>

DevCard_Mvc/Views/Home/Details.cshtml
@model Project

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<style>
    img{
        width:100px;
    }
    .projects {
        margin: 0 40px;
    }
</style>
<div class="projects">
    <h4>Project</h4>
    <hr />
    <table class="table table-bordered table-hover client-quote">
        <tr>

            <th>Id</th>
            <th>Title</th>
            <th>Description</th>
            <th>Image</th>
            <th>Client</th>
        </tr>
        <tr>
            `
            <td>@Model.Id</td>
            <td>@Model.Name</td>
            <td>@Model.Description</td>
            <td><img src="~/assets/images/project/@Model.Image" /></td>
            <td>@Model.Client</td>
        </tr>
    </table>
    <a asp-action="Index">Back to List</a>
</div>

DevCard_Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<section class="about-me-section p-3 p-lg-5 theme-bg-light">
    <div class="container">
        <div class="profile-teaser media flex-column flex-lg-row">
            <img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="assets/images/me.jpeg" alt="">
            <div class="media-body">
                <h2 class="name font-weight-bold mb-1">حسین عباس آبادی</h2>
                <div class="tagline mb-3">برنامه نویس ارشد</div>
                <div class="bio mb-4">
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از
                    طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و
                    جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
                </div>
                <div class="mb-4">
                    <a class="btn btn-primary mr-2 mb-3" href="http://www.atriya.com">
                        <i class="fas fa-arrow-alt-circle-right ml-2"></i><span class="d-none d-md-inline">
                            برو
                            به
                        </span> آتریا
                    </a>
                    <a class="btn btn-secondary mb-3" href="#">
                        <i class="fas fa-file-alt ml-2"></i>
                        <span class="d-none d-md-inline">مشاهده </span> نمونه کارها
                    </a>
                </div>
            </div>

        </div>
    </div>
</section>
@await Component.InvokeAsync("Projects")
<div class="container">
    <hr>
</div>
@await Component.InvokeAsync("Articles")

DevCard_Mvc/Views/Shared/Footer.cshtml
<footer class="footer text-center py-4">
    <small class="copyright">
        تولید شده توسط &copy; <a href="http://www.atriya.com" target="_blank">
            موسسه آموزشی
            آتریا
        </a>
    </small>
</footer>

DevCard_Mvc/Views/Shared/Header.cshtml
<header class="header text-center">
    <div class="force-overflow">
        <h1 class="blog-name pt-lg-4 mb-0"><a href="index.html">حسعباس آبادی</a></h1>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navigation" class="collapse navbar-collapse flex-column">
                <div class="profile-section pt-3 pt-lg-0">
                    <img class="profile-image mb-3 rounded-circle mx-auto" src="~/assets/images/me.jpeg" alt="image">

                    <div class="bio mb-3">
                    </div>
                    <ul class="social-list list-inline py-2 mx-auto">
                        <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
                        <li class="list-inline-item">
                            <a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
                    </ul>
                    <hr>
                </div>
                <ul class="navbar-nav flex-column text-right">
                    <li class="nav-item">
                        <a class="nav-link" href="/">
                            <i class="fas fa-user fa-fw ml-2"></i>صفحه اصلی<span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/home/contact">
                            <i class="fas fa-envelope-open-text fa-fw ml-2"></i>ارتباط با ما
                        </a>
                    </li>
                </ul>
            </div>

        </nav>
    </div>
</header>

DevCard_Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">

<head>
    <title>DevCard از موسسه </title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.ico">

    <script defer src="~/assets/fontawesome/js/all.js"></script>
    <link id="theme-style" rel="stylesheet" href="~/assets/css/theme-1.css">
    <link id="theme-style" rel="stylesheet" href="~/assets/css/style.css">

</head>

<body>

   <partial name="Header"/>

    <div class="main-wrapper">
        @RenderBody()
       <partial name="Footer"/>

    </div>

    <!-- Javascript -->
    <script src="~/assets/plugins/jquery-3.4.1.min.js"></script>
    <script src="~/assets/plugins/popper.min.js"></script>
    <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>